# Generated by Django 4.0.4 on 2022-06-02 10:00

from django.db import migrations, models
import tiers.models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tiers.models.tier_image_file_path),
        ),
    ]
