# Generated by Django 4.0.4 on 2022-06-02 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tiers.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiers', '0003_remove_tier_image_remove_tier_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tiers.models.tier_image_file_path)),
                ('link_original', models.CharField(blank=True, max_length=255)),
                ('link_200px', models.CharField(blank=True, max_length=255)),
                ('link_400px', models.CharField(blank=True, max_length=255)),
                ('expiring_link_val', models.IntegerField(blank=True)),
                ('expiring_link', models.CharField(blank=True, max_length=255)),
                ('custom_expiring_link', models.CharField(blank=True, max_length=255)),
                ('custom_link_height', models.IntegerField(blank=True)),
                ('custom_link_width', models.IntegerField(blank=True)),
                ('custom_link', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tier',
            name='custom_images',
            field=models.ManyToManyField(to='tiers.customimages'),
        ),
    ]
