# Generated by Django 4.0.4 on 2022-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_plan',
            field=models.CharField(blank=True, choices=[('bp', 'BASIC PLAN'), ('pp', 'PREMIUM PLAN'), ('ep', 'ENTERPRISE PLAN'), ('aa', 'ADMIN PLAN')], default='bp', max_length=2),
        ),
    ]
