# Generated by Django 4.0.4 on 2022-05-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perm',
            field=models.CharField(choices=[('bp', 'BASIC PLAN'), ('pp', 'PREMIUM PLAN'), ('dp', 'ENTERPRISE PLAN')], default='bp', max_length=2),
        ),
    ]
