# Generated by Django 4.0.5 on 2022-06-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_account_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_plan',
            field=models.CharField(default='bp', max_length=2),
        ),
    ]
