# Generated by Django 4.0.4 on 2022-05-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='perm',
        ),
        migrations.AddField(
            model_name='user',
            name='account_plan',
            field=models.CharField(choices=[('bp', 'BASIC PLAN'), ('pp', 'PREMIUM PLAN'), ('ep', 'ENTERPRISE PLAN'), ('aa', 'APP ADMINISTRATOR')], default='bp', max_length=2),
        ),
    ]
