# Generated by Django 4.0.4 on 2022-05-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_perm_user_account_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_plan',
            field=models.CharField(choices=[('bp', 'BASIC PLAN'), ('pp', 'PREMIUM PLAN'), ('ep', 'ENTERPRISE PLAN')], default='bp', max_length=2),
        ),
    ]
